name: get_pdf
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.0.3+5
  pdf: ^1.11.0
  file: ^5.2.1
  permission_handler: ^5.0.1
  file_picker: ^1.13.3
  share_extend: ^1.1.9
  camera: ^0.5.8+5
  shared_preferences: ^0.5.10
  flutter_speed_dial: ^1.2.5
  image_editor: ^0.7.1
  image_cropper: ^1.3.1
  pdf_viewer_plugin: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/fileIcon.png
    - assets/indocanner-logo.png
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Anton
      fonts:
        - asset: assets/Anton-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: MedriendaOne
      fonts:
        - asset: assets/MeriendaOne-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

